In [1]:
import pandas as pd
import numpy as np
import yfinance as yf

from data_collector import DataCollector

In [2]:
companies_df = pd.read_csv(r'data\sp500-with-gics.csv')
companies_df

,Unnamed: 0,Ticker,CompanyName,Sector,SubIndustry,HQLocation,DateFirstAdded,CIK,FoundedYear,QuoteURL,...,HQLocationWikiPage,SectorId,Sector.1,IndustryGroupId,IndustryGroup,IndustryId,Industry,SubIndustryId,SubIndustry.1,SubIndustryDescription
0,0,MMM,3M Company,Industrials,Industrial Conglomerates,"St. Paul, Minnesota",1976-08-09,66740,1902,https://www.nyse.com/quote/XNYS:MMM,...,"/wiki/St._Paul,_Minnesota",20,Industrials,2010,Capital Goods,201050,Industrial Conglomerates,20105010,Industrial Conglomerates,Diversified industrial companies with business...
1,1,ABT,Abbott Laboratories,Health Care,Health Care Equipment,"North Chicago, Illinois",1964-03-31,1800,1888,https://www.nyse.com/quote/XNYS:ABT,...,"/wiki/North_Chicago,_Illinois",35,Health Care,3510,Health Care Equipment & Services,351010,Health Care Equipment & Supplies,35101010,Health Care Equipment,Manufacturers of health care equipment and dev...
2,2,ABBV,AbbVie Inc.,Health Care,Pharmaceuticals,"North Chicago, Illinois",2012-12-31,1551152,2013 (1888),https://www.nyse.com/quote/XNYS:ABBV,...,"/wiki/North_Chicago,_Illinois",35,Health Care,3520,"Pharmaceuticals, Biotechnology & Life Sciences",352020,Pharmaceuticals,35202010,Pharmaceuticals,"Companies engaged in the research, development..."
3,3,ABMD,ABIOMED Inc,Health Care,Health Care Equipment,"Danvers, Massachusetts",2018-05-31,815094,1981,http://www.nasdaq.com/symbol/abmd,...,"/wiki/Danvers,_Massachusetts",35,Health Care,3510,Health Care Equipment & Services,351010,Health Care Equipment & Supplies,35101010,Health Care Equipment,Manufacturers of health care equipment and dev...
4,4,ACN,Accenture plc,Information Technology,IT Consulting & Other Services,"Dublin, Ireland",2011-07-06,1467373,1989,https://www.nyse.com/quote/XNYS:ACN,...,"/wiki/Dublin,_Ireland",45,Information Technology,4510,Software & Services,451020,IT Services,45102010,IT Consulting & Other Services,Providers of information technology and system...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
500,500,YUM,Yum! Brands Inc,Consumer Discretionary,Restaurants,"Louisville, Kentucky",1997-10-06,1041061,1997,https://www.nyse.com/quote/XNYS:YUM,...,"/wiki/Louisville,_Kentucky",25,Consumer Discretionary,2530,Consumer Services,253010,"Hotels, Restaurants & Leisure",25301040,Restaurants,"Owners and operators of restaurants, bars, pub..."
501,501,ZBRA,Zebra Technologies,Information Technology,Electronic Equipment & Instruments,"Lincolnshire, Illinois",2019-12-23,877212,1969,http://www.nasdaq.com/symbol/zbra,...,"/wiki/Lincolnshire,_Illinois",45,Information Technology,4520,Technology Hardware & Equipment,452030,"Electronic Equipment, Instruments & Components",45203010,Electronic Equipment & Instruments,Manufacturers of electronic equipment and inst...
502,502,ZBH,Zimmer Biomet,Health Care,Health Care Equipment,"Warsaw, Indiana",2001-08-07,1136869,1927,https://www.nyse.com/quote/XNYS:ZBH,...,"/wiki/Warsaw,_Indiana",35,Health Care,3510,Health Care Equipment & Services,351010,Health Care Equipment & Supplies,35101010,Health Care Equipment,Manufacturers of health care equipment and dev...
503,503,ZION,Zions Bancorp,Financials,Regional Banks,"Salt Lake City, Utah",2001-06-22,109380,1873,http://www.nasdaq.com/symbol/zion,...,"/wiki/Salt_Lake_City,_Utah",40,Financials,4010,Banks,401010,Banks,40101015,Regional Banks,Commercial banks whose businesses are derived ...
504,504,ZTS,Zoetis,Health Care,Pharmaceuticals,"Florham Park, New Jersey",2013-06-21,1555280,1952,https://www.nyse.com/quote/XNYS:ZTS,...,"/wiki/Florham_Park,_New_Jersey",35,Health Care,3520,"Pharmaceuticals, Biotechnology & Life Sciences",352020,Pharmaceuticals,35202010,Pharmaceuticals,"Companies engaged in the research, development..."

In [3]:

tickers = list(companies_df["Ticker"])
tickers

['MMM',
 'ABT',
 'ABBV',
 'ABMD',
 'ACN',
 'ATVI',
 'ADBE',
 'AMD',
 'AAP',
 'AES',
 'AFL',
 'A',
 'APD',
 'AKAM',
 'ALK',
 'ALB',
 'ARE',
 'ALXN',
 'ALGN',
 'ALLE',
 'LNT',
 'ALL',
 'GOOGL',
 'GOOG',
 'MO',
 'AMZN',
 'AMCR',
 'AEE',
 'AAL',
 'AEP',
 'AXP',
 'AIG',
 'AMT',
 'AWK',
 'AMP',
 'ABC',
 'AME',
 'AMGN',
 'APH',
 'ADI',
 'ANSS',
 'ANTM',
 'AON',
 'AOS',
 'APA',
 'AAPL',
 'AMAT',
 'APTV',
 'ADM',
 'ANET',
 'AJG',
 'AIZ',
 'T',
 'ATO',
 'ADSK',
 'ADP',
 'AZO',
 'AVB',
 'AVY',
 'BKR',
 'BLL',
 'BAC',
 'BK',
 'BAX',
 'BDX',
 'BRK.B',
 'BBY',
 'BIO',
 'BIIB',
 'BLK',
 'BA',
 'BKNG',
 'BWA',
 'BXP',
 'BSX',
 'BMY',
 'AVGO',
 'BR',
 'BF.B',
 'CHRW',
 'COG',
 'CDNS',
 'CPB',
 'COF',
 'CAH',
 'KMX',
 'CCL',
 'CARR',
 'CTLT',
 'CAT',
 'CBOE',
 'CBRE',
 'CDW',
 'CE',
 'CNC',
 'CNP',
 'CERN',
 'CF',
 'SCHW',
 'CHTR',
 'CVX',
 'CMG',
 'CB',
 'CHD',
 'CI',
 'CINF',
 'CTAS',
 'CSCO',
 'C',
 'CFG',
 'CTXS',
 'CLX',
 'CME',
 'CMS',
 'KO',
 'CTSH',
 'CL',
 'CMCSA',
 'CMA',
 'CAG',
 'CXO',
 'COP',
 'ED',
 'STZ',
 'COO',
 'CPRT',
 'GLW',
 'CTVA',
 'COST',
 'CCI',
 'CSX',
 'CMI',
 'CVS',
 'DHI',
 'DHR',
 'DRI',
 'DVA',
 'DE',
 'DAL',
 'XRAY',
 'DVN',
 'DXCM',
 'FANG',
 'DLR',
 'DFS',
 'DISCA',
 'DISCK',
 'DISH',
 'DG',
 'DLTR',
 'D',
 'DPZ',
 'DOV',
 'DOW',
 'DTE',
 'DUK',
 'DRE',
 'DD',
 'DXC',
 'EMN',
 'ETN',
 'EBAY',
 'ECL',
 'EIX',
 'EW',
 'EA',
 'EMR',
 'ENPH',
 'ETR',
 'EOG',
 'EFX',
 'EQIX',
 'EQR',
 'ESS',
 'EL',
 'ETSY',
 'EVRG',
 'ES',
 'RE',
 'EXC',
 'EXPE',
 'EXPD',
 'EXR',
 'XOM',
 'FFIV',
 'FB',
 'FAST',
 'FRT',
 'FDX',
 'FIS',
 'FITB',
 'FE',
 'FRC',
 'FISV',
 'FLT',
 'FLIR',
 'FLS',
 'FMC',
 'F',
 'FTNT',
 'FTV',
 'FBHS',
 'FOXA',
 'FOX',
 'BEN',
 'FCX',
 'GPS',
 'GRMN',
 'IT',
 'GD',
 'GE',
 'GIS',
 'GM',
 'GPC',
 'GILD',
 'GL',
 'GPN',
 'GS',
 'GWW',
 'HAL',
 'HBI',
 'HIG',
 'HAS',
 'HCA',
 'PEAK',
 'HSIC',
 'HSY',
 'HES',
 'HPE',
 'HLT',
 'HFC',
 'HOLX',
 'HD',
 'HON',
 'HRL',
 'HST',
 'HWM',
 'HPQ',
 'HUM',
 'HBAN',
 'HII',
 'IEX',
 'IDXX',
 'INFO',
 'ITW',
 'ILMN',
 'INCY',
 'IR',
 'INTC',
 'ICE',
 'IBM',
 'IP',
 'IPG',
 'IFF',
 'INTU',
 'ISRG',
 'IVZ',
 'IPGP',
 'IQV',
 'IRM',
 'JKHY',
 'J',
 'JBHT',
 'SJM',
 'JNJ',
 'JCI',
 'JPM',
 'JNPR',
 'KSU',
 'K',
 'KEY',
 'KEYS',
 'KMB',
 'KIM',
 'KMI',
 'KLAC',
 'KHC',
 'KR',
 'LB',
 'LHX',
 'LH',
 'LRCX',
 'LW',
 'LVS',
 'LEG',
 'LDOS',
 'LEN',
 'LLY',
 'LNC',
 'LIN',
 'LYV',
 'LKQ',
 'LMT',
 'L',
 'LOW',
 'LUMN',
 'LYB',
 'MTB',
 'MRO',
 'MPC',
 'MKTX',
 'MAR',
 'MMC',
 'MLM',
 'MAS',
 'MA',
 'MKC',
 'MXIM',
 'MCD',
 'MCK',
 'MDT',
 'MRK',
 'MET',
 'MTD',
 'MGM',
 'MCHP',
 'MU',
 'MSFT',
 'MAA',
 'MHK',
 'TAP',
 'MDLZ',
 'MNST',
 'MCO',
 'MS',
 'MOS',
 'MSI',
 'MSCI',
 'NDAQ',
 'NTAP',
 'NFLX',
 'NWL',
 'NEM',
 'NWSA',
 'NWS',
 'NEE',
 'NLSN',
 'NKE',
 'NI',
 'NSC',
 'NTRS',
 'NOC',
 'NLOK',
 'NCLH',
 'NOV',
 'NRG',
 'NUE',
 'NVDA',
 'NVR',
 'ORLY',
 'OXY',
 'ODFL',
 'OMC',
 'OKE',
 'ORCL',
 'OTIS',
 'PCAR',
 'PKG',
 'PH',
 'PAYX',
 'PAYC',
 'PYPL',
 'PNR',
 'PBCT',
 'PEP',
 'PKI',
 'PRGO',
 'PFE',
 'PM',
 'PSX',
 'PNW',
 'PXD',
 'PNC',
 'POOL',
 'PPG',
 'PPL',
 'PFG',
 'PG',
 'PGR',
 'PLD',
 'PRU',
 'PEG',
 'PSA',
 'PHM',
 'PVH',
 'QRVO',
 'PWR',
 'QCOM',
 'DGX',
 'RL',
 'RJF',
 'RTX',
 'O',
 'REG',
 'REGN',
 'RF',
 'RSG',
 'RMD',
 'RHI',
 'ROK',
 'ROL',
 'ROP',
 'ROST',
 'RCL',
 'SPGI',
 'CRM',
 'SBAC',
 'SLB',
 'STX',
 'SEE',
 'SRE',
 'NOW',
 'SHW',
 'SPG',
 'SWKS',
 'SLG',
 'SNA',
 'SO',
 'LUV',
 'SWK',
 'SBUX',
 'STT',
 'STE',
 'SYK',
 'SIVB',
 'SYF',
 'SNPS',
 'SYY',
 'TMUS',
 'TROW',
 'TTWO',
 'TPR',
 'TGT',
 'TEL',
 'FTI',
 'TDY',
 'TFX',
 'TER',
 'TSLA',
 'TXN',
 'TXT',
 'TMO',
 'TJX',
 'TSCO',
 'TT',
 'TDG',
 'TRV',
 'TFC',
 'TWTR',
 'TYL',
 'TSN',
 'UDR',
 'ULTA',
 'USB',
 'UAA',
 'UA',
 'UNP',
 'UAL',
 'UNH',
 'UPS',
 'URI',
 'UHS',
 'UNM',
 'VLO',
 'VAR',
 'VTR',
 'VRSN',
 'VRSK',
 'VZ',
 'VRTX',
 'VFC',
 'VIAC',
 'VTRS',
 'V',
 'VNT',
 'VNO',
 'VMC',
 'WRB',
 'WAB',
 'WMT',
 'WBA',
 'DIS',
 'WM',
 'WAT',
 'WEC',
 'WFC',
 'WELL',
 'WST',
 'WDC',
 'WU',
 'WRK',
 'WY',
 'WHR',
 'WMB',
 'WLTW',
 'WYNN',
 'XEL',
 'XRX',
 'XLNX',
 'XYL',
 'YUM',
 'ZBRA',
 'ZBH',
 'ZION',
 'ZTS']

In [9]:
data_collector = DataCollector()
data_collector.set_tickers(tickers)

In [11]:
data_collector.download_data("1999-12-01", "2024-01-01", "1d")

[*********************100%***********************]  505 of 505 completed

40 Failed downloads:
['SIVB', 'BF.B']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1d 1999-12-01 -> 2024-01-01)')
['ATVI', 'DISCA', 'XLNX', 'VIAC', 'ABMD', 'DRE', 'DISH', 'PEAK', 'FBHS', 'BLL', 'PBCT', 'TWTR', 'FRC', 'PKI', 'RE', 'FB', 'FLIR', 'KSU', 'COG', 'CERN', 'NLOK', 'HFC', 'ALXN', 'BRK.B', 'ANTM', 'WLTW', 'INFO', 'VAR', 'PXD', 'ABC', 'CTXS', 'MXIM', 'WRK', 'DISCK', 'NLSN', 'CXO', 'FLT']: YFTzMissingError('$%ticker%: possibly delisted; no timezone found')
['LB']: YFPricesMissingError('$%ticker%: possibly delisted; no price data found  (1d 1999-12-01 -> 2024-01-01) (Yahoo error = "Data doesn\'t exist for startDate = 944024400, endDate = 1704085200")')

In [13]:
raw_data = data_collector.get_raw_data()
raw_data.info()
adj_close_df = raw_data["Adj Close"]

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 6059 entries, 1999-12-01 00:00:00+00:00 to 2023-12-29 00:00:00+00:00
Columns: 3960 entries, ('Adj Close', 'A') to ('Volume', 'ZTS')
dtypes: float64(3611), int64(349)
memory usage: 183.1 MB

In [19]:
adj_close_df

Ticker,A,AAL,AAP,AAPL,ABBV,ABC,ABMD,ABT,ACN,ADBE,...,XLNX,XOM,XRAY,XRX,XYL,YUM,ZBH,ZBRA,ZION,ZTS
Date,,,,,,,,,,,,,,,,,,,,,
1999-12-01 00:00:00+00:00,26.412981,NaN,NaN,0.791284,NaN,NaN,NaN,10.038709,NaN,16.516727,...,NaN,20.507168,6.851254,43.274231,NaN,5.301508,NaN,26.444445,46.484074,NaN
1999-12-02 00:00:00+00:00,27.143471,NaN,NaN,0.845987,NaN,NaN,NaN,10.076414,NaN,17.028509,...,NaN,20.402292,6.705094,42.865986,NaN,5.244504,NaN,25.555555,46.884415,NaN
1999-12-03 00:00:00+00:00,27.374151,NaN,NaN,0.882936,NaN,NaN,NaN,10.038709,NaN,16.547743,...,NaN,20.514931,6.979146,42.355663,NaN,5.211928,NaN,25.944445,48.085449,NaN
1999-12-06 00:00:00+00:00,28.143091,NaN,NaN,0.890614,NaN,NaN,NaN,9.753804,NaN,15.663750,...,NaN,20.848944,6.741635,42.559795,NaN,5.220074,NaN,25.583332,46.884415,NaN
1999-12-07 00:00:00+00:00,27.835514,NaN,NaN,0.904530,NaN,NaN,NaN,9.602974,NaN,15.043405,...,NaN,20.848944,6.778176,41.641239,NaN,5.244504,NaN,24.777779,45.283070,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-12-22 00:00:00+00:00,139.570007,14.31,61.250000,193.600006,154.940002,NaN,NaN,109.029999,354.450012,598.750000,...,NaN,101.910004,35.220001,18.700001,112.639999,130.000000,120.559998,269.410004,44.000000,194.979996
2023-12-26 00:00:00+00:00,139.809998,14.11,60.919998,193.050003,154.619995,NaN,NaN,109.230003,353.429993,598.260010,...,NaN,102.139999,35.540001,18.809999,113.620003,130.259995,121.419998,275.500000,44.880001,195.500000
2023-12-27 00:00:00+00:00,139.820007,13.99,61.560001,193.149994,154.880005,NaN,NaN,109.790001,353.820007,596.080017,...,NaN,101.660004,35.630001,18.940001,114.379997,130.839996,121.129997,275.790009,44.509998,196.899994
2023-12-28 00:00:00+00:00,139.770004,13.98,61.490002,193.580002,154.750000,NaN,NaN,110.400002,351.589996,595.520020,...,NaN,100.190002,35.590000,18.580000,114.320000,130.520004,121.629997,275.350006,44.660000,197.160004
2023-12-29 00:00:00+00:00,139.029999,13.74,61.029999,192.529999,154.970001,NaN,NaN,110.070000,350.910004,596.599976,...,NaN,99.980003,35.590000,18.330000,114.360001,130.660004,121.699997,273.329987,43.869999,197.369995

In [17]:
nan_count_dict = {}

for column in adj_close_df.columns:
    nan_count_dict[column] = len(adj_close_df[adj_close_df[column].isna()].index.tolist())

In [18]:
nan_count_dict

{'A': 0,
 'AAL': 1463,
 'AAP': 500,
 'AAPL': 0,
 'ABBV': 3291,
 'ABC': 6059,
 'ABMD': 6059,
 'ABT': 0,
 'ACN': 411,
 'ADBE': 0,
 'ADI': 0,
 'ADM': 0,
 'ADP': 0,
 'ADSK': 0,
 'AEE': 0,
 'AEP': 0,
 'AES': 0,
 'AFL': 0,
 'AIG': 0,
 'AIZ': 1049,
 'AJG': 0,
 'AKAM': 0,
 'ALB': 0,
 'ALGN': 293,
 'ALK': 0,
 'ALL': 0,
 'ALLE': 3513,
 'ALXN': 6059,
 'AMAT': 0,
 'AMCR': 3133,
 'AMD': 0,
 'AME': 0,
 'AMGN': 0,
 'AMP': 1455,
 'AMT': 0,
 'AMZN': 0,
 'ANET': 3650,
 'ANSS': 0,
 'ANTM': 6059,
 'AON': 0,
 'AOS': 0,
 'APA': 0,
 'APD': 0,
 'APH': 0,
 'APTV': 3011,
 'ARE': 0,
 'ATO': 0,
 'ATVI': 6059,
 'AVB': 0,
 'AVGO': 2434,
 'AVY': 0,
 'AWK': 2109,
 'AXP': 0,
 'AZO': 0,
 'BA': 0,
 'BAC': 0,
 'BAX': 0,
 'BBY': 0,
 'BDX': 0,
 'BEN': 0,
 'BF.B': 6059,
 'BIIB': 0,
 'BIO': 0,
 'BK': 0,
 'BKNG': 0,
 'BKR': 0,
 'BLK': 0,
 'BLL': 6059,
 'BMY': 0,
 'BR': 1835,
 'BRK.B': 6059,
 'BSX': 0,
 'BWA': 0,
 'BXP': 0,
 'C': 0,
 'CAG': 0,
 'CAH': 0,
 'CARR': 5106,
 'CAT': 0,
 'CB': 0,
 'CBOE': 2649,
 'CBRE': 1136,
 'CCI': 0,
 'CCL': 0,
 'CDNS': 0,
 'CDW': 3413,
 'CE': 1291,
 'CERN': 6059,
 'CF': 1431,
 'CFG': 3726,
 'CHD': 0,
 'CHRW': 0,
 'CHTR': 2538,
 'CI': 0,
 'CINF': 0,
 'CL': 0,
 'CLX': 0,
 'CMA': 0,
 'CMCSA': 0,
 'CME': 757,
 'CMG': 1546,
 'CMI': 0,
 'CMS': 0,
 'CNC': 510,
 'CNP': 0,
 'COF': 0,
 'COG': 6059,
 'COO': 0,
 'COP': 0,
 'COST': 0,
 'CPB': 0,
 'CPRT': 0,
 'CRM': 1144,
 'CSCO': 0,
 'CSX': 0,
 'CTAS': 0,
 'CTLT': 3688,
 'CTSH': 0,
 'CTVA': 4900,
 'CTXS': 6059,
 'CVS': 0,
 'CVX': 0,
 'CXO': 6059,
 'D': 0,
 'DAL': 1864,
 'DD': 0,
 'DE': 0,
 'DFS': 1893,
 'DG': 2504,
 'DGX': 0,
 'DHI': 0,
 'DHR': 0,
 'DIS': 0,
 'DISCA': 6059,
 'DISCK': 6059,
 'DISH': 6059,
 'DLR': 1234,
 'DLTR': 0,
 'DOV': 0,
 'DOW': 4854,
 'DPZ': 1157,
 'DRE': 6059,
 'DRI': 0,
 'DTE': 0,
 'DUK': 0,
 'DVA': 0,
 'DVN': 0,
 'DXC': 0,
 'DXCM': 1348,
 'EA': 0,
 'EBAY': 0,
 'ECL': 0,
 'ED': 0,
 'EFX': 0,
 'EIX': 0,
 'EL': 0,
 'EMN': 0,
 'EMR': 0,
 'ENPH': 3102,
 'EOG': 0,
 'EQIX': 176,
 'EQR': 0,
 'ES': 0,
 'ESS': 0,
 'ETN': 0,
 'ETR': 0,
 'ETSY': 3866,
 'EVRG': 0,
 'EW': 80,
 'EXC': 0,
 'EXPD': 0,
 'EXPE': 1416,
 'EXR': 1181,
 'F': 0,
 'FANG': 3238,
 'FAST': 0,
 'FB': 6059,
 'FBHS': 6059,
 'FCX': 0,
 'FDX': 0,
 'FE': 0,
 'FFIV': 0,
 'FIS': 391,
 'FISV': 5910,
 'FITB': 0,
 'FLIR': 6059,
 'FLS': 0,
 'FLT': 6059,
 'FMC': 0,
 'FOX': 4849,
 'FOXA': 4848,
 'FRC': 6059,
 'FRT': 0,
 'FTI': 388,
 'FTNT': 2507,
 'FTV': 4173,
 'GD': 0,
 'GE': 0,
 'GILD': 0,
 'GIS': 0,
 'GL': 0,
 'GLW': 0,
 'GM': 2759,
 'GOOG': 1184,
 'GOOGL': 1184,
 'GPC': 0,
 'GPN': 283,
 'GPS': 0,
 'GRMN': 259,
 'GS': 0,
 'GWW': 0,
 'HAL': 0,
 'HAS': 0,
 'HBAN': 0,
 'HBI': 1700,
 'HCA': 2835,
 'HD': 0,
 'HES': 0,
 'HFC': 6059,
 'HIG': 0,
 'HII': 2843,
 'HLT': 3530,
 'HOLX': 0,
 'HON': 0,
 'HPE': 3995,
 'HPQ': 0,
 'HRL': 0,
 'HSIC': 0,
 'HST': 0,
 'HSY': 0,
 'HUM': 0,
 'HWM': 4257,
 'IBM': 0,
 'ICE': 1499,
 'IDXX': 0,
 'IEX': 0,
 'IFF': 0,
 'ILMN': 166,
 'INCY': 0,
 'INFO': 6059,
 'INTC': 0,
 'INTU': 0,
 'IP': 0,
 'IPG': 0,
 'IPGP': 1769,
 'IQV': 3379,
 'IR': 4389,
 'IRM': 0,
 'ISRG': 137,
 'IT': 0,
 'ITW': 0,
 'IVZ': 0,
 'J': 0,
 'JBHT': 0,
 'JCI': 0,
 'JKHY': 0,
 'JNJ': 0,
 'JNPR': 0,
 'JPM': 0,
 'K': 0,
 'KEY': 0,
 'KEYS': 3744,
 'KHC': 3921,
 'KIM': 0,
 'KLAC': 0,
 'KMB': 0,
 'KMI': 2817,
 'KMX': 0,
 'KO': 0,
 'KR': 0,
 'KSU': 6059,
 'L': 0,
 'LB': 6059,
 'LDOS': 1729,
 'LEG': 0,
 'LEN': 0,
 'LH': 0,
 'LHX': 0,
 'LIN': 0,
 'LKQ': 965,
 'LLY': 0,
 'LMT': 0,
 'LNC': 0,
 'LNT': 0,
 'LOW': 0,
 'LRCX': 0,
 'LUMN': 0,
 'LUV': 0,
 'LVS': 1266,
 'LW': 4264,
 'LYB': 2616,
 'LYV': 1523,
 'MA': 1629,
 'MAA': 0,
 'MAR': 0,
 'MAS': 0,
 'MCD': 0,
 'MCHP': 0,
 'MCK': 0,
 'MCO': 0,
 'MDLZ': 386,
 'MDT': 0,
 'MET': 87,
 'MGM': 0,
 'MHK': 0,
 'MKC': 0,
 'MKTX': 1239,
 'MLM': 0,
 'MMC': 0,
 'MMM': 0,
 'MNST': 0,
 'MO': 0,
 'MOS': 0,
 'MPC': 2909,
 'MRK': 0,
 'MRO': 0,
 'MS': 0,
 'MSCI': 2001,
 'MSFT': 0,
 'MSI': 0,
 'MTB': 0,
 'MTD': 0,
 'MU': 0,
 'MXIM': 6059,
 'NCLH': 3303,
 'NDAQ': 646,
 'NEE': 0,
 'NEM': 0,
 'NFLX': 620,
 'NI': 0,
 'NKE': 0,
 'NLOK': 6059,
 'NLSN': 6059,
 'NOC': 0,
 'NOV': 0,
 'NOW': 3165,
 'NRG': 1005,
 'NSC': 0,
 'NTAP': 0,
 'NTRS': 0,
 'NUE': 0,
 'NVDA': 0,
 'NVR': 0,
 'NWL': 0,
 'NWS': 3407,
 'NWSA': 3407,
 'O': 0,
 'ODFL': 0,
 'OKE': 0,
 'OMC': 0,
 'ORCL': 0,
 'ORLY': 0,
 'OTIS': 5106,
 'OXY': 0,
 'PAYC': 3614,
 'PAYX': 0,
 'PBCT': 6059,
 'PCAR': 0,
 'PEAK': 6059,
 'PEG': 0,
 'PEP': 0,
 'PFE': 0,
 'PFG': 474,
 'PG': 0,
 'PGR': 0,
 'PH': 0,
 'PHM': 0,
 'PKG': 40,
 'PKI': 6059,
 'PLD': 0,
 'PM': 2083,
 'PNC': 0,
 'PNR': 0,
 'PNW': 0,
 'POOL': 0,
 'PPG': 0,
 'PPL': 0,
 'PRGO': 0,
 'PRU': 510,
 'PSA': 0,
 'PSX': 3110,
 'PVH': 0,
 'PWR': 0,
 'PXD': 6059,
 'PYPL': 3921,
 'QCOM': 0,
 'QRVO': 3795,
 'RCL': 0,
 'RE': 6059,
 'REG': 0,
 'REGN': 0,
 'RF': 0,
 'RHI': 0,
 'RJF': 0,
 'RL': 0,
 'RMD': 0,
 'ROK': 0,
 'ROL': 0,
 'ROP': 0,
 'ROST': 0,
 'RSG': 0,
 'RTX': 0,
 'SBAC': 0,
 'SBUX': 0,
 'SCHW': 0,
 'SEE': 0,
 'SHW': 0,
 'SIVB': 6059,
 'SJM': 0,
 'SLB': 0,
 'SLG': 0,
 'SNA': 0,
 'SNPS': 0,
 'SO': 0,
 'SPG': 0,
 'SPGI': 0,
 'SRE': 0,
 'STE': 0,
 'STT': 0,
 'STX': 760,
 'STZ': 0,
 'SWK': 0,
 'SWKS': 0,
 'SYF': 3688,
 'SYK': 0,
 'SYY': 0,
 'T': 0,
 'TAP': 0,
 'TDG': 1579,
 'TDY': 0,
 'TEL': 1893,
 'TER': 0,
 'TFC': 0,
 'TFX': 0,
 'TGT': 0,
 'TJX': 0,
 'TMO': 0,
 'TMUS': 1854,
 'TPR': 215,
 'TROW': 0,
 'TRV': 0,
 'TSCO': 0,
 'TSLA': 2659,
 'TSN': 0,
 'TT': 0,
 'TTWO': 0,
 'TWTR': 6059,
 'TXN': 0,
 'TXT': 0,
 'TYL': 0,
 'UA': 4102,
 'UAA': 1501,
 'UAL': 1553,
 'UDR': 0,
 'UHS': 0,
 'ULTA': 1986,
 'UNH': 0,
 'UNM': 0,
 'UNP': 0,
 'UPS': 0,
 'URI': 0,
 'USB': 0,
 'V': 2085,
 'VAR': 6059,
 'VFC': 0,
 'VIAC': 6059,
 'VLO': 0,
 'VMC': 0,
 'VNO': 0,
 'VNT': 5237,
 'VRSK': 2477,
 'VRSN': 0,
 'VRTX': 0,
 'VTR': 0,
 'VTRS': 0,
 'VZ': 0,
 'WAB': 0,
 'WAT': 0,
 'WBA': 0,
 'WDC': 0,
 'WEC': 0,
 'WELL': 0,
 'WFC': 0,
 'WHR': 0,
 'WLTW': 6059,
 'WM': 0,
 'WMB': 0,
 'WMT': 0,
 'WRB': 0,
 'WRK': 6059,
 'WST': 0,
 'WU': 1718,
 'WY': 0,
 'WYNN': 728,
 'XEL': 0,
 'XLNX': 6059,
 'XOM': 0,
 'XRAY': 0,
 'XRX': 0,
 'XYL': 2986,
 'YUM': 0,
 'ZBH': 415,
 'ZBRA': 0,
 'ZION': 0,
 'ZTS': 3312}